export const LARGE_QUOTE_DATABASE = [
  "Associate yourself with men of good quality... for 'tis better to be alone than in bad company. — George Washington",
  "He that can have patience can have what he will. — Benjamin Franklin",
  "Well done is better than well said. — Benjamin Franklin",
  "The harder the conflict, the more glorious the triumph. — Thomas Paine",
  "I have not yet begun to fight! — John Paul Jones",
  "Give me liberty, or give me death! — Patrick Henry",
  "It is during our darkest moments that we must focus to see the light. — George Washington",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "If your actions inspire others to dream more, learn more, do more and become more, you are a leader. — John Quincy Adams",
  "I must study politics and war that my sons may have liberty to study mathematics and philosophy. — John Adams",
  "Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight. — Benjamin Franklin",
  "It does not take a majority to prevail, but rather an irate, tireless minority, keen on setting brushfires of freedom in the minds of men. — Samuel Adams",
  "Without freedom of thought, there can be no such thing as wisdom. — Benjamin Franklin",
  "Whatever is worth doing at all is worth doing well. — Philip Stanhope",
  "We must all hang together, or assuredly we shall all hang separately. — Benjamin Franklin",
  "Honesty is the first chapter in the book of wisdom. — Thomas Jefferson",
  "Never trouble another for what you can do yourself. — Thomas Jefferson",
  "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. — Thomas Jefferson",
  "In matters of style, swim with the current; in matters of principle, stand like a rock. — Thomas Jefferson",
  "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
  "Do not worry; eat three square meals a day; say your prayers; be courteous to your creditors; keep your digestion good; exercise; go slow and easy. — Abraham Lincoln",
  "Nothing can stop the man with the right mental attitude from achieving his goal. — Thomas Jefferson",
  "Delay is preferable to error. — Thomas Jefferson",
  "When angry, count to ten before you speak. If very angry, count to one hundred. — Thomas Jefferson",
  "The Constitution only guarantees the American people the right to pursue happiness. You have to catch it yourself. — Benjamin Franklin",
  "By failing to prepare, you are preparing to fail. — Benjamin Franklin",
  "Tell me and I forget, teach me and I may remember, involve me and I learn. — Benjamin Franklin",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "Either write something worth reading or do something worth writing. — Benjamin Franklin",
  "Never leave that till tomorrow which you can do today. — Benjamin Franklin",
  "Diligence is the mother of good luck. — Benjamin Franklin",
  "He that is good for making excuses is seldom good for anything else. — Benjamin Franklin",
  "Lost time is never found again. — Benjamin Franklin",
  "Genius without education is like silver in the mine. — Benjamin Franklin",
  "Dost thou love life? Then do not squander time, for that is the stuff life is made of. — Benjamin Franklin",
  "The man who does things makes mistakes, but he never makes the biggest mistake of all—doing nothing. — Benjamin Franklin",
  "Be at war with your vices, at peace with your neighbors, and let every new year find you a better man. — Benjamin Franklin",
  "There are no gains without pains. — Benjamin Franklin",
  "Without continual growth and progress, success has no meaning. — Benjamin Franklin",
  "Some people die at 25 and aren't buried until 75. — Benjamin Franklin",
  "Do not fear mistakes. You will know failure. Continue to reach out. — Benjamin Franklin",
  "To succeed, jump as quickly at opportunities as you do at conclusions. — Benjamin Franklin",
  "Write your injuries in dust, your benefits in marble. — Benjamin Franklin",
  "Happiness depends more on the inward disposition of mind than on outward circumstances. — Benjamin Franklin",
  "Being ignorant is not so much a shame, as being unwilling to learn. — Benjamin Franklin",
  "If a man empties his purse into his head, no one can take it from him. — Benjamin Franklin",
  "The best investment is in the tools of one's own trade. — Benjamin Franklin",
  "He that lives upon hope will die fasting. — Benjamin Franklin",
  "To be humble to superiors is duty, to equals courtesy, to inferiors nobleness. — Benjamin Franklin",
  "We are all born ignorant, but one must work hard to remain stupid. — Benjamin Franklin",
  "The way to see by faith is to shut the eye of reason. — Benjamin Franklin",
  "Human felicity is produced by little advantages that occur every day. — Benjamin Franklin",
  "When you're finished changing, you're finished. — Benjamin Franklin",
  "Since thou art not sure of a minute, throw not away an hour. — Benjamin Franklin",
  "It takes many good deeds to build a good reputation, and only one bad one to lose it. — Benjamin Franklin",
  "Be slow in choosing a friend, slower in changing. — Benjamin Franklin",
  "Observe all men, thyself most. — Benjamin Franklin",
  "Whatever is begun in anger ends in shame. — Benjamin Franklin",
  "I didn't fail the test. I just found 100 ways to do it wrong. — Benjamin Franklin",
  "Our greatest glory is not in never falling, but in rising every time we fall. — George Washington",
  "Discipline is the soul of an army. — George Washington",
  "It is better to offer no excuse than a bad one. — George Washington",
  "Happiness and moral duty are inseparably connected. — George Washington",
  "Perseverance and spirit have done wonders in all ages. — George Washington",
  "We ought not to look back unless it is to derive useful lessons from past errors. — George Washington",
  "Associate with men of good quality if you esteem your own reputation. — George Washington",
  "Guard against the impostures of pretended patriotism. — George Washington",
  "Worry is the interest paid by those who borrow trouble. — George Washington",
  "Undertake not what you cannot perform, but be careful to keep your promise. — George Washington",
  "True friendship is a plant of slow growth. — George Washington",
  "Labor to keep alive in your breast that little spark of celestial fire called conscience. — George Washington",
  "If the freedom of speech is taken away then dumb and silent we may be led, like sheep to the slaughter. — George Washington",
  "Be courteous to all, but intimate with few. — George Washington",
  "Ninety-nine percent of the failures come from people who have the habit of making excuses. — George Washington",
  "Let your heart feel for the afflictions and distress of everyone. — George Washington",
  "Maintain the character of an honest man. — George Washington",
  "Do not let your happiness depend on something you may lose. — Thomas Jefferson",
  "I like the dreams of the future better than the history of the past. — Thomas Jefferson",
  "The glow of one warm thought is to me worth more than money. — Thomas Jefferson",
  "Leave all the afternoon for exercise and recreation, which are as necessary as reading. — Thomas Jefferson",
  "Nothing gives one person so much advantage over another as to remain always cool and unruffled. — Thomas Jefferson",
  "Tranquility and occupation give you happiness. — Thomas Jefferson",
  "Do you want to know who you are? Don't ask. Act! — Thomas Jefferson",
  "He who knows best knows how little he knows. — Thomas Jefferson",
  "Whenever you do a thing, act as if all the world were watching. — Thomas Jefferson",
  "The man who reads nothing at all is better educated than the man who reads nothing but newspapers. — Thomas Jefferson",
  "It is in our lives and not our words that our religion must be read. — Thomas Jefferson",
  "I cannot live without books. — Thomas Jefferson",
  "Never spend your money before you have earned it. — Thomas Jefferson",
  "The God who gave us life gave us liberty at the same time. — Thomas Jefferson",
  "Walking is the best possible exercise. Habituate yourself to walk very far. — Thomas Jefferson",
  "He who permits himself to tell a lie once, finds it much easier to do it a second and third time. — Thomas Jefferson",
  "Enlighten the people generally, and tyranny will vanish like evil spirits at the dawn of day. — Thomas Jefferson",
  "Pride costs us more than hunger, thirst, and cold. — Thomas Jefferson",
  "I hope our wisdom will grow with our power. — Thomas Jefferson",
  "The Advertisement is the most truthful part of a newspaper. — Thomas Jefferson",
  "Dependence begets subservience and venality. — Thomas Jefferson",
  "Facts are stubborn things. — John Adams",
  "There are two ways to conquer and enslave a country. One is by the sword. The other is by debt. — John Adams",
  "Liberty cannot be preserved without general knowledge among the people. — John Adams",
  "Old minds are like old horses; you must exercise them if you wish to keep them in working order. — John Adams",
  "Courage and perseverance have a magical talisman, before which difficulties disappear. — John Quincy Adams",
  "The advancement and diffusion of knowledge is the only guardian of true liberty. — James Madison",
  "The truth is that all men having power ought to be mistrusted. — James Madison",
  "Knowledge will forever govern ignorance. — James Madison",
  "The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants. — Thomas Jefferson",
  "We must consult our means rather than our wishes. — George Washington",
  "Liberty, when it begins to take root, is a plant of rapid growth. — George Washington",
  "Let us raise a standard to which the wise and honest can repair. — George Washington",
  "Rise early, that by habit it may become familiar, agreeable, healthy, and profitable. — George Washington",
  "To contract new debts is not the way to pay old ones. — George Washington",
  "If we desire to avoid insult, we must be able to repel it. — George Washington",
  "Always vote for principle, though you may vote alone. — John Quincy Adams",
  "To furnish the means of acquiring knowledge is the greatest benefit that can be conferred upon mankind. — John Quincy Adams",
  "The influence of each human being on others in this life is a kind of immortality. — John Quincy Adams",
  "Try and fail, but don't fail to try. — John Quincy Adams",
  "Duty is ours, results are God's. — John Quincy Adams",
  "Always stand on principle, even if you stand alone. — John Quincy Adams",
  "To be good and to do good is all we have to do. — John Adams",
  "The jaws of power are always open to devour. — John Adams",
  "Let us dare to read, think, speak, and write. — John Adams",
  "A government of laws, and not of men. — John Adams",
  "Property must be secured, or liberty cannot exist. — John Adams",
  "The longer I live, the more I read, the less I seem to know. — John Adams",
  "Arms in the hands of citizens may be used at individual discretion in private self defense. — John Adams",
  "Nearly all men can stand adversity, but if you want to test a man's character, give him power. — Abraham Lincoln",
  "Whatever you are, be a good one. — Abraham Lincoln",
  "The best way to predict your future is to create it. — Abraham Lincoln",
  "I am a slow walker, but I never walk back. — Abraham Lincoln",
  "Those who deny freedom to others deserve it not for themselves. — Abraham Lincoln",
  "Give me six hours to chop down a tree and I will spend the first four sharpening the axe. — Abraham Lincoln",
  "I destroy my enemies when I make them my friends. — Abraham Lincoln",
  "You cannot escape the responsibility of tomorrow by evading it today. — Abraham Lincoln",
  "Things may come to those who wait, but only the things left by those who hustle. — Abraham Lincoln",
  "Character is like a tree and reputation like a shadow. — Abraham Lincoln",
  "The best thing about the future is that it comes one day at a time. — Abraham Lincoln",
  "Be sure you put your feet in the right place, then stand firm. — Abraham Lincoln",
  "We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses. — Abraham Lincoln",
  "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
  "No man is good enough to govern another man without that other's consent. — Abraham Lincoln",
  "When I do good, I feel good. When I do bad, I feel bad. That's my religion. — Abraham Lincoln",
  "Discipline is choosing between what you want now and what you want most. — Abraham Lincoln",
  "Always bear in mind that your own resolution to succeed is more important than any other. — Abraham Lincoln",
  "A house divided against itself cannot stand. — Abraham Lincoln",
  "The ballot is stronger than the bullet. — Abraham Lincoln",
  "I am not bound to win, but I am bound to be true. — Abraham Lincoln",
  "He has a right to criticize, who has a heart to help. — Abraham Lincoln",
  "I have always found that mercy bears richer fruits than strict justice. — Abraham Lincoln",
  "Most folks are as happy as they make up their minds to be. — Abraham Lincoln",
  "No man has a good enough memory to be a successful liar. — Abraham Lincoln",
  "I will prepare and some day my chance will come. — Abraham Lincoln",
  "When you reach the end of your rope, tie a knot and hang on. — Abraham Lincoln",
  "Determine that the thing can and shall be done, and then we shall find the way. — Abraham Lincoln",
  "I hold it that a little rebellion now and then is a good thing. — Thomas Jefferson",
  "Educate and inform the whole mass of the people. — Thomas Jefferson",
  "The boisterous sea of liberty is never without a wave. — Thomas Jefferson",
  "Timid men prefer the calm of despotism to the tempestuous sea of liberty. — Thomas Jefferson",
  "I predict future happiness for Americans if they can prevent the government from wasting the labors of the people. — Thomas Jefferson",
  "Rightful liberty is unobstructed action according to our will within limits drawn around us by the equal rights of others. — Thomas Jefferson",
  "Eternal vigilance is the price of liberty. — Thomas Jefferson",
  "A wise and frugal government shall leave men free to regulate their own pursuits. — Thomas Jefferson",
  "Every citizen should be a soldier. — Thomas Jefferson",
  "Where the press is free and every man able to read, all is safe. — Thomas Jefferson",
  "The care of human life and happiness is the first and only object of good government. — Thomas Jefferson",
  "One man with courage is a majority. — Thomas Jefferson",
  "If a nation expects to be ignorant and free, it expects what never was and never will be. — Thomas Jefferson",
  "It is error alone which needs the support of government. Truth can stand by itself. — Thomas Jefferson",
  "Power is not alluring to pure minds. — Thomas Jefferson",
  "Our liberty depends on the freedom of the press. — Thomas Jefferson",
  "The whole art of government consists in the art of being honest. — Thomas Jefferson",
  "Every difference of opinion is not a difference of principle. — Thomas Jefferson",
  "History, in general, only informs us what bad government is. — Thomas Jefferson",
  "Were we directed from Washington when to sow and when to reap, we should soon want bread. — Thomas Jefferson",
  "Resistance to tyrants is obedience to God. — Thomas Jefferson",
  "A Bill of Rights is what the people are entitled to. — Thomas Jefferson",
  "Laws made by common consent must not be trampled on by individuals. — George Washington",
  "Firearms stand next in importance to the Constitution itself. — George Washington",
  "To be prepared for war is one of the most effective means of preserving peace. — George Washington",
  "The administration of justice is the firmest pillar of government. — George Washington",
  "Human rights can only be assured among a virtuous people. — George Washington",
  "Real men despise battle, but will never run from it. — George Washington",
  "Observe good faith and justice toward all nations. — George Washington",
  "A free people ought not only to be armed, but disciplined. — George Washington",
  "Those who stand for nothing fall for anything. — Alexander Hamilton",
  "A promise must never be broken. — Alexander Hamilton",
  "There is a certain enthusiasm in liberty, that makes human nature rise above itself. — Alexander Hamilton",
  "Real firmness is good for anything; strut is good for nothing. — Alexander Hamilton",
  "Man is either governed by his own laws—freedom—or by the laws of another—slavery. — Alexander Hamilton",
  "I never expect to see a perfect work from an imperfect man. — Alexander Hamilton"
];

/**
 * FitDadForge Placeholder Component
 * This default export is required by Expo Router to identify this file as a valid route-ready asset.
 */
export default function Quotes() {
  return null;
}